### ISSUE TITLE
Credit API is missing the approval code in the response object

### ISSUE THREAD

**Issue by dtarachan** [CyberSource/cybersource-rest-client-dotnetstandard#12]
Hi,

It appears that the Swagger/OpenAPI json file that you using for generating the SDK is missing the ApprovalCode in the success response object under the ProcessorInformation node. Can you confirm if the ApprovalCode should be present? The ApprovalCode is available on the web playground for the API: https://developer.cybersource.com/api-reference-assets/index.html#payments_credit_process-a-credit

Thanks.

**Comment by monu-kumar-visa** [comment]
Hi,
The `ApprovalCode` field in `ProcessorInformation` has been added in version 0.0.13 and subsequent versions.
