### ISSUE TITLE
Start and End log messages are wrong

### ISSUE THREAD

**Issue by sipsorcery** [CyberSource/cybersource-rest-client-dotnetstandard#32]
Looks like something has gone wrong with your openapi generation scripts.

There are multiple examples like this [one](https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/blob/6e108238f8151c38f4e6558343e42e158fcdcc84/cybersource-rest-client-netstandard/cybersource-rest-client-netstandard/Api/PayerAuthenticationApi.cs#L575).

```
public async System.Threading.Tasks.Task<RiskV1AuthenticationSetupsPost201Response> PayerAuthSetupAsync (PayerAuthSetupRequest payerAuthSetupRequest)
{
	logger.Debug("CALLING API \"PayerAuthSetupAsync\" STARTED");
	ApiResponse<RiskV1AuthenticationSetupsPost201Response> localVarResponse = await PayerAuthSetupAsyncWithHttpInfo(payerAuthSetupRequest);
	logger.Debug("CALLING API \"PayerAuthSetupAsync\" STARTED");
	return localVarResponse.Data;

}
```

**Comment by gnongsie** [comment]
Hi @sipsorcery , GREAT CATCH!!!!!

This is a copy-paste error in the template and I have corrected it. Expect this to be fixed in the next release.
