### ISSUE TITLE
RestClient is not configured correctly

### ISSUE THREAD

**Issue by orbis-pbowman** [CyberSource/cybersource-rest-client-dotnetstandard#72]
**Describe the bug**
The options set on the RestClient are ignored as they should be set on the RestClientOptions passed to the RestClient constructor. In previous versions of RestClient, it was possible to set options on the RestClient instance directly and even after construction these would be used. In newer versions of RestClient, including that used in 0.0.1.28 of this package, only the options passed into the constructor are used to configure the HttpClient - any set later are ignored. This library does that - it builds but it doesn't work. The newest version of RestClient makes it a compile time issue by copying the options to a read only version of the options.

In our case, we use a proxy, and it would be nice to set other options on the RestClient too.

**To** Reproduce
Use the library and see the proxy and other others not being set correctly.

**Expected** behavior
The options should be set when RestClient is constructed.

I should add that we're upgrading from 0.0.1.5 to 0.0.1.28 due to the (request-target) issue that must be resolved by 22 Jan, so time is of the essence for this fix.

**Comment by orbis-pbowman** [comment]
The proxy appears to also be set on each http request (rendering setting the option on the RestClient unnecessary), so the proxy is working ok. The user agent is also set this way. I suspect that client certificates (which we do not use in our company) are not set up in RestClient.

It would be nice to see the library cleaned up - understanding how it works involves reading the source code, which is a challenge.

**Comment by gaubansa** [comment]
Hi @orbis-pbowman 
This issue has been fixed and released in v0.0.1.31
