### ISSUE TITLE
Exception when duplicate response headers are encountered

### ISSUE THREAD

**Issue by fdgit** [CyberSource/cybersource-rest-client-dotnetstandard#94]
The csharp samples are failing with an exception. For example, if one runs the RetrieveCustomer sample, it fails with:

System.ArgumentException: 'An item with the same key has already been added. Key: Vary'
on the line
PostCustomerRequest result = apiInstance.GetCustomer(customerTokenId);
The headers being returned from test include 3 "Vary" headers, which cause an exception because the headers are placed in a dictionary. (This just started happening - I first noticed it on 8/12/24.)
I believe duplicate response headers should be in comma delimited lists in the response, so it seems that the response headers have changed recently. (I also posted this on cybersource-rest-client-dotnet at https://github.com/CyberSource/cybersource-rest-client-dotnet/issues/182)

**Comment by dshchupak** [comment]
I am experiencing this issue as well. Is there a plan to either accept @fdgit fix or revert the change that caused this issue?

**Comment by gaubansa** [comment]
Thanks for reporting the issue for duplicate response key in SDK. We have fixed the issue in SDK from version v0.0.1.37 onwards.
